"""Pydantic Schemas"""

from app.schemas.admin import (
    AdminChangePassword,
    AdminCreate,
    AdminLogin,
    AdminResetPassword,
    AdminResponse,
    AdminUpdate,
    TokenResponse,
)
from app.schemas.common import (
    BaseSchema,
    IDSchema,
    PaginationParams,
    TimestampSchema,
)
from app.schemas.order import (
    OrderCreate,
    OrderDetailResponse,
    OrderItemCreate,
    OrderItemResponse,
    OrderListResponse,
    OrderLogResponse,
    OrderQueryByEmail,
    OrderStatus,
    OrderUpdate,
    PaymentCallbackData,
    PaymentInitRequest,
    PaymentInitResponse,
)
from app.schemas.platform import (
    AnnouncementCreate,
    AnnouncementListResponse,
    AnnouncementResponse,
    AnnouncementUpdate,
    BannerCreate,
    BannerResponse,
    BannerUpdate,
    EmailConfigCreate,
    EmailConfigResponse,
    EmailConfigUpdate,
    FooterLinkCreate,
    FooterLinkResponse,
    FooterLinkType,
    FooterLinkUpdate,
    PlatformConfigCreate,
    PlatformConfigResponse,
    PlatformConfigUpdate,
)
from app.schemas.product import (
    CategoryCreate,
    CategoryResponse,
    CategoryTreeResponse,
    CategoryUpdate,
    FeeType,
    InventoryItemBatchCreate,
    InventoryItemCreate,
    InventoryItemResponse,
    PaymentMethodAdminResponse,
    PaymentMethodCreate,
    PaymentMethodResponse,
    PaymentMethodUpdate,
    ProductCreate,
    ProductDetailResponse,
    ProductImageCreate,
    ProductImageResponse,
    ProductListResponse,
    ProductTagCreate,
    ProductTagResponse,
    ProductType,
    ProductUpdate,
)

__all__ = [
    # Common
    "BaseSchema",
    "IDSchema",
    "TimestampSchema",
    "PaginationParams",
    # Enums
    "FooterLinkType",
    "ProductType",
    "FeeType",
    "OrderStatus",
    # Admin
    "AdminLogin",
    "AdminCreate",
    "AdminUpdate",
    "AdminChangePassword",
    "AdminResetPassword",
    "AdminResponse",
    "TokenResponse",
    # Platform
    "PlatformConfigCreate",
    "PlatformConfigUpdate",
    "PlatformConfigResponse",
    "EmailConfigCreate",
    "EmailConfigUpdate",
    "EmailConfigResponse",
    "AnnouncementCreate",
    "AnnouncementUpdate",
    "AnnouncementResponse",
    "AnnouncementListResponse",
    "BannerCreate",
    "BannerUpdate",
    "BannerResponse",
    "FooterLinkCreate",
    "FooterLinkUpdate",
    "FooterLinkResponse",
    # Product
    "CategoryCreate",
    "CategoryUpdate",
    "CategoryResponse",
    "CategoryTreeResponse",
    "PaymentMethodCreate",
    "PaymentMethodUpdate",
    "PaymentMethodResponse",
    "PaymentMethodAdminResponse",
    "ProductImageCreate",
    "ProductImageResponse",
    "ProductTagCreate",
    "ProductTagResponse",
    "ProductCreate",
    "ProductUpdate",
    "ProductListResponse",
    "ProductDetailResponse",
    "InventoryItemCreate",
    "InventoryItemBatchCreate",
    "InventoryItemResponse",
    # Order
    "OrderItemCreate",
    "OrderItemResponse",
    "OrderCreate",
    "OrderUpdate",
    "OrderListResponse",
    "OrderDetailResponse",
    "OrderQueryByEmail",
    "OrderLogResponse",
    "PaymentInitRequest",
    "PaymentInitResponse",
    "PaymentCallbackData",
]
